<h3>1% dla OPP</h3>
<ul>
	<li><a href="index.php?p=jeden_procent&a=prawa_darczyncy" id="prawa_darczyncy" title="Przekazujesz 1% podatku? Zobacz jakie masz prawa" <?php if ($_GET['a']=='prawa_darczyncy' || !$_GET['a']) {echo ' style="font-weight: bold;"';} ?>>Przekazujesz 1% podatku? Zobacz jakie masz prawa</a></li>
	<li><a href="index.php?p=jeden_procent&a=1procent_w_polsce" id="1procent_w_polsce" title="Jak przekazać 1 procent podatku na rzecz Organizacji Pożytku Publicznego." <?php if ($_GET['a']=='1procent_w_polsce') {echo ' style="font-weight: bold;"';} ?>>1% podatku w Polsce - historia i tendencje</a></li>
	<li><a href="index.php?p=jeden_procent&a=komu_pomagaja_polacy" id="komu_pomagaja_polacy" title="1 procent - komu i dlaczego chcą pomagać Polacy?" <?php if ($_GET['a']=='komu_pomagaja_polacy') {echo ' style="font-weight: bold;"';} ?>>1 procent - komu i dlaczego chcą pomagać Polacy?</a></li>
	<li><a href="index.php?p=jeden_procent&a=opinie_polakow" id="opinie_polakow" title="Opinie Polaków na temat OPP - badania" <?php if ($_GET['a']=='opinie_polakow') {echo ' style="font-weight: bold;"';} ?>>Opinie Polaków na temat OPP - badania</a></li>
	<li><a href="index.php?p=jeden_procent&a=kto_moze_przekazac" id="kto_moze_przekazac" title="Kto może przekazać 1% podatku?" <?php if ($_GET['a']=='kto_moze_przekazac') {echo ' style="font-weight: bold;"';} ?>>Kto może przekazać 1% podatku?</a></li>
	<li><a href="index.php?p=jeden_procent&a=jak_przekazac" id="jak_przekazac" title="Jak przekazać 1 procent podatku na rzecz Organizacji Pożytku Publicznego." <?php if ($_GET['a']=='jak_przekazac') {echo ' style="font-weight: bold;"';} ?>>Jak przekazać 1 procent podatku na rzecz OPP ?</a></li>
	<li><a href="index.php?p=jeden_procent&a=wplyw_statusu_opp" id="wplyw_statusu_opp" title="Wpływ statusu OPP na działalność organizacji" <?php if ($_GET['a']=='wplyw_statusu_opp') {echo ' style="font-weight: bold;"';} ?>>Wpływ statusu OPP na działalność organizacji</a></li>
	<li><a href="index.php?p=jeden_procent&a=przywileje" id="przywileje" title="Przywileje i możliwości, jakie daje status OPP" <?php if ($_GET['a']=='przywileje') {echo ' style="font-weight: bold;"';} ?>>Przywileje i możliwości, jakie daje status OPP</a></li>
	<li><a href="index.php?p=jeden_procent&a=ryczalt" id="ryczalt" title="Jeden procent podatku na rzecz OPP - podatnicy opodatkowani w formie ryczałtu od przychodów ewidencjonowanych." <?php if ($_GET['a']=='ryczalt') {echo ' style="font-weight: bold;"';} ?>>Dla podatników płacących ryczałt</a></li>
	<li><a href="index.php?p=jeden_procent&a=podsumowanie" id="podsumowanie" title="Podsumowanie 1% podatku na rzecz organizacji pożytku publicznego za lata 2003-2007." <?php if ($_GET['a']=='podsumowanie') {echo ' style="font-weight: bold;"';} ?>>Podsumowanie za lata 2003-2007</a></li>
</ul>